[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-assoc = "1.0.0"
context = { path = "../context" }

[dev-dependencies]
pretty_assertions = "1.3.0"
